#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# bloqueia uso de --no-verify (opcional)
if echo "$HUSKY_GIT_PARAMS" | grep -q -- "--no-verify"; then
  echo "🚫 O uso de '--no-verify' não é permitido!"
  exit 1
fi

# 1) corrige e formata só o que está staged
npx lint-staged || exit 1

# 2) type-check do projeto todo
npm run type-check || exit 1
